# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2017-01-27 17:46
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Listing',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=30)),
                ('image', models.FileField(upload_to='')),
                ('description', models.TextField(max_length=300)),
                ('category', models.IntegerField(choices=[(1, 'Door'), (2, 'Transom'), (3, 'Cabinet'), (4, 'Miscellaneous')], default=1)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.Admin')),
            ],
        ),
    ]
