# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-12-18 21:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='listing',
            name='category',
            field=models.IntegerField(choices=[(1, 'Door'), (2, 'Transom'), (3, 'Cabinet'), (4, 'Miscellaneous')], default=1),
        ),
        migrations.AlterField(
            model_name='listing',
            name='image',
            field=models.FileField(upload_to=''),
        ),
    ]
