# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-12-11 23:47
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('messaging', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='message',
            old_name='Content',
            new_name='body',
        ),
        migrations.RenameField(
            model_name='message',
            old_name='Recipient',
            new_name='recipient',
        ),
        migrations.RenameField(
            model_name='message',
            old_name='Sender',
            new_name='sender',
        ),
        migrations.RenameField(
            model_name='message',
            old_name='Subject',
            new_name='subject',
        ),
    ]
