# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-12-12 01:14
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0002_auto_20161211_2344'),
    ]

    operations = [
        migrations.CreateModel(
            name='Appointment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start', models.DateTimeField()),
                ('duration', models.TimeField()),
                ('comments', models.TextField(max_length=160)),
                ('admin', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='appointmentAdmin', to='accounts.Admin')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='appointmentClient', to='accounts.Client')),
            ],
        ),
    ]
