# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-12-13 16:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='comments',
            field=models.TextField(blank=True, max_length=160, null=True),
        ),
    ]
