# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-12-18 23:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0003_auto_20161218_1803'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='duration',
            field=models.TimeField(),
        ),
    ]
